window.PROMPTS_DATA = [
  {"id":1,"title":"Minecraft Voxel Sandbox","difficulty":"Very Hard"},
  {"id":2,"title":"GTA Open World Action","difficulty":"Very Hard"},
  {"id":3,"title":"FNAF Animatronic Horror","difficulty":"Hard"},
  {"id":4,"title":"Fortnite Battle Royale","difficulty":"Very Hard"},
  {"id":5,"title":"SubwaySurfers Endless Runner","difficulty":"Medium"},
  {"id":6,"title":"Portal Physics Puzzle","difficulty":"Very Hard"},
  {"id":7,"title":"SpeedGame High Speed Platformer","difficulty":"Hard"},
  {"id":8,"title":"Original Game Blank Canvas","difficulty":"Hard"},
  {"id":9,"title":"FL Studio Browser DAW","difficulty":"Very Hard"},
  {"id":10,"title":"Astra Showcase Website","difficulty":"Light"},
  {"id":11,"title":"Daily Ship Log","difficulty":"Medium"},
  {"id":12,"title":"Anime Gacha Action RPG","difficulty":"Very Hard"},
  {"id":13,"title":"Roblox Studio Lite","difficulty":"Hard"},
  {"id":14,"title":"Premiere Pro Lite","difficulty":"Hard"},
  {"id":15,"title":"Original Rhythm Game + Chart Editor","difficulty":"Hard"},
  {"id":16,"title":"3D Animation Editor","difficulty":"Hard"},
  {"id":17,"title":"After Effects Lite","difficulty":"Hard"},
  {"id":18,"title":"FNF Style Rhythm Game Original Song","difficulty":"Hard"},
  {"id":19,"title":"3D Obby Speedrun Game","difficulty":"Medium"},
  {"id":20,"title":"Original First Person Horror Game","difficulty":"Hard"},
  {"id":21,"title":"Physics Sandbox","difficulty":"Medium"},
  {"id":22,"title":"Factory Tycoon Game","difficulty":"Hard"},
  {"id":23,"title":"Music Visualizer","difficulty":"Light"},
  {"id":24,"title":"Game Launcher","difficulty":"Light"},
  {"id":25,"title":"Character Customizer","difficulty":"Light"},
  {"id":26,"title":"Retro Arcade Hub","difficulty":"Light"},
  {"id":27,"title":"Shader Playground","difficulty":"Light"},
  {"id":28,"title":"3D Parkour Playground","difficulty":"Medium"},
  {"id":29,"title":"Boss Fight Game","difficulty":"Medium"},
  {"id":30,"title":"Rhythm Boss Battle","difficulty":"Medium"},
  {"id":31,"title":"Physics Destruction Playground","difficulty":"Medium"},
  {"id":32,"title":"Drone Simulator","difficulty":"Medium"},
  {"id":33,"title":"Fake Malware Desktop Game","difficulty":"Medium"},
  {"id":34,"title":"Racing Time Trial","difficulty":"Medium"},
  {"id":35,"title":"Conveyor Tycoon","difficulty":"Medium"},
  {"id":36,"title":"Security Camera Horror","difficulty":"Medium"},
  {"id":37,"title":"Interactive Music Video","difficulty":"Medium"},
  {"id":38,"title":"Multiplayer Parkour Race","difficulty":"Medium"},
  {"id":39,"title":"FNF Multiplayer Battle","difficulty":"Medium"},
  {"id":40,"title":"Multiplayer Horror Escape","difficulty":"Hard"},
  {"id":41,"title":"Multiplayer Party Minigame Collection","difficulty":"Medium"},
  {"id":42,"title":"Coop Spaceship Crew Game","difficulty":"Hard"},
  {"id":43,"title":"Team Objective Shooter","difficulty":"Hard"}
];
