// Generates charts/neon-meridian.json + js/default-chart.js from song-data.js
import { writeFileSync, mkdirSync } from 'node:fs';
import { deriveChart, chartStats, SONG_LENGTH } from '../js/song-data.js';

const chart = deriveChart();
const stats = chartStats(chart);
mkdirSync('charts', { recursive: true });
writeFileSync('charts/neon-meridian.json', JSON.stringify(chart, null, 1));
const js = '// Auto-generated by scripts/gen-chart.mjs — embedded fallback of charts/neon-meridian.json\n' +
  'export const DEFAULT_CHART = ' + JSON.stringify(chart) + ';\n';
writeFileSync('js/default-chart.js', js);
console.log('notes:', stats.total, 'taps:', stats.taps, 'holds:', stats.holds,
  'nps:', stats.nps, 'length(s):', stats.durSec);
