import { createGame } from "../Multiplayer Horror Escape-opencode/server.mjs";
const game = createGame(1234);
const log = [];
const ws = { id: "A", query: new URLSearchParams(), send: s => log.push(JSON.parse(s)), close() {} };
const h = game.create({ debug: true });
h.open(ws);
h.message(ws, JSON.stringify({ t: "hello", c: "c1", n: "ALPHA" }));
h.message(ws, JSON.stringify({ t: "ready", v: true }));
h.message(ws, JSON.stringify({ t: "start" }));
for (let i = 0; i < 80; i++) h.tick(0.05);
console.log("pre-dbg:", (() => { const s = [...log].reverse().find(m => m.t === "snap"); return s.state + "/" + s.phase; })());
h.message(ws, JSON.stringify({ t: "dbg", k: "power" }));
for (let i = 0; i < 5; i++) h.tick(0.05);
let s = [...log].reverse().find(m => m.t === "snap");
console.log("post-dbg-power:", s.state + "/" + s.phase, "mon:", !!s.mon);
h.message(ws, JSON.stringify({ t: "dbg", k: "win" }));
h.tick(0.05);
s = [...log].reverse().find(m => m.t === "snap");
console.log("post-dbg-win:", s.state, "end:", !!s.end);
