"""Post-process: song.wav + song_events.json -> js/music-data.js + js/audio-data.js
Band energies (low/mid/high) baked at 50 fps as base64 uint8 curves."""
import numpy as np
import wave, json, os, base64

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FPS = 50
WIN = 2048
HOP = SR_HOP = None

with wave.open(os.path.join(HERE, "song.wav"), "rb") as w:
    SR = w.getframerate()
    n = w.getnframes()
    pcm = np.frombuffer(w.readframes(n), dtype=np.int16).reshape(-1, 2)
mono = pcm.astype(np.float32).mean(axis=1) / 32768.0

hop = SR // FPS                       # 960 @48k -> exactly 50 fps
nframes = int((len(mono) - WIN) // hop)
win = np.hanning(WIN).astype(np.float32)
freqs = np.fft.rfftfreq(WIN, 1 / SR)
BANDS = [(20, 160), (160, 2000), (2000, 11000)]
masks = [((freqs >= lo) & (freqs <= hi)).astype(np.float64) for lo, hi in BANDS]
norms = [m.sum() for m in masks]

cur = 0
energies = [[], [], []]
for i in range(nframes):
    seg = mono[cur:cur + WIN] * win
    spec = np.abs(np.fft.rfft(seg)) ** 2
    for b in range(3):
        energies[b].append(float((spec * masks[b]).sum() / norms[b]))
    cur += hop

vals_u8 = []
for b in range(3):
    e = np.array(energies[b])
    db = 20.0 * np.log10(e + 1e-8)
    lo_p, hi_p = np.percentile(db, 6), np.percentile(db, 99.0)
    v = np.clip((db - lo_p) / (hi_p - lo_p), 0, 1)
    out = np.empty_like(v)
    acc = v[0]
    for i in range(len(v)):           # EMA smoothing
        acc = 0.62 * acc + 0.38 * v[i]
        out[i] = acc
    vals_u8.append((out * 255).astype(np.uint8))

def b64(a):
    return base64.b64encode(a.tobytes()).decode()

ev = json.load(open(os.path.join(HERE, "song_events.json")))

def compact_hits(hits):
    kinds = {k: i for i, k in enumerate(
        ["kick", "snare", "clap", "hat", "ohat", "tom", "crash", "boom"])}
    out = []
    for t, k, v in hits:
        if k in kinds:
            out.append([round(t, 3), kinds[k], v])
    return out

music = dict(
    title="NEON DRIFT",
    artist="OX//ALPHA",
    bpm=ev["bpm"], duration=ev["duration"], fps=FPS,
    sections=ev["sections"], beats=[round(b, 3) for b in ev["beats"]],
    hits=compact_hits(ev["hits"]), notes=[[round(n[0], 3), n[1], round(n[2], 3), n[3]]
                                          for n in ev["notes"]],
    bands=dict(low=b64(vals_u8[0]), mid=b64(vals_u8[1]),
               high=b64(vals_u8[2])),
)

js = "// generated by postprocess.py - do not edit\nwindow.MUSIC=" + \
     json.dumps(music, separators=(",", ":")) + ";"
with open(os.path.join(ROOT, "js", "music-data.js"), "w") as f:
    f.write(js)

mp3 = open(os.path.join(HERE, "song.mp3"), "rb").read()
uri = "data:audio/mpeg;base64," + base64.b64encode(mp3).decode()
with open(os.path.join(ROOT, "js", "audio-data.js"), "w") as f:
    f.write("// generated - embedded track\nwindow.SONG_DATA_URI=\"" + uri + "\";")

print("music-data.js:", os.path.getsize(os.path.join(ROOT, "js", "music-data.js")))
print("audio-data.js:", os.path.getsize(os.path.join(ROOT, "js", "audio-data.js")))
print("frames:", nframes, "~=", int(ev['duration'] * FPS))
